package com.brightpattern.bpcontactcenter.entity

internal class FieldName {
    companion object {
        const val CASE_ID = "case_id"
        const val CHAT = "chat"
        const val CHAT_ID = "chat_id"
        const val CREATED_TIME = "created_time"
        const val DEVICE_TOKEN = "android_firebase_device_token"
        const val DISPLAY_NAME = "display_name"
        const val EVENT = "event"
        const val EVENTS = "events"
        const val EWT = "ewt"
        const val FILE_ID = "file_id"
        const val FILE_NAME = "file_name"
        const val FILE_TYPE = "file_type"
        const val FIRST_NAME = "first_name"
        const val FORM_DATA = "form_data"
        const val FROM = "from"
        const val IS_NEW_CHAT = "is_new_chat"
        const val LAST_NAME = "last_name"
        const val MSG = "msg"
        const val MSG_ID = "msg_id"
        const val NOTIFICATION_CHAT_ID = "chatID"
        const val PARAMETERS = "parameters"
        const val PARTY_ID = "party_id"
        const val PHONE_NUMBER = "phone_number"
        const val REF_MSG_ID = "ref_msg_id"
        const val REQ_ID = "req_id"
        const val SERVER_VERSION = "server_version"
        const val SESSIONS = "sessions"
        const val STATE = "state"
        const val TIMESTAMP = "timestamp"
    }
}